# Generated by Django 5.2.8 on 2025-11-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_name',
            field=models.CharField(blank=True, help_text='GitHub repository (format: owner/repo)', max_length=200),
        ),
    ]
