# Generated by Django 5.2.8 on 2025-11-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_repo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_status_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic status updates from GitHub'),
        ),
        migrations.AddField(
            model_name='project',
            name='auto_sync_issues',
            field=models.BooleanField(default=False, help_text='Automatically sync GitHub issues to tasks'),
        ),
        migrations.AddField(
            model_name='project',
            name='stale_days',
            field=models.IntegerField(default=7, help_text='Days without commits before marked STALE'),
        ),
    ]
